-- DropForeignKey
ALTER TABLE "STUDENTS" DROP CONSTRAINT "STUDENTS_user_id_fkey";

-- AddForeignKey
ALTER TABLE "STUDENTS" ADD CONSTRAINT "STUDENTS_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "USERS"("id") ON DELETE CASCADE ON UPDATE CASCADE;
